main_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MainBlogBundle:Default:index }
MainBlogBundle_post:
    resource: "@MainBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

MainBlogBundle_category:
    resource: "@MainBlogBundle/Resources/config/routing/category.yml"
    prefix:   /category

MainBlogBundle_product:
    resource: "@MainBlogBundle/Resources/config/routing/product.yml"
    prefix:   /product
