main_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MainBlogBundle:Default:index }
MainBlogBundle_post:
    resource: "@MainBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

