parameters:
#    main_blog.example.class: Main\BlogBundle\Example

services:
#    main_blog.example:
#        class: %main_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
