parameters:
#    test_company_test.example.class: TestCompany\TestBundle\Example

services:
#    test_company_test.example:
#        class: %test_company_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
