Main\BlogBundle\Entity\Post:
    type: entity
    table: posts
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: '250'
        body:
            type: text
        published:
            type: datetime
    lifecycleCallbacks: {  }
